apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flutter-web
  template:
    metadata:
      labels:
        app: flutter-web
    spec:
      containers:
        - name: flutter-web
          image: hakimsamouh/flutter-web:dev-1.0.0-eb4df97
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: dockerhub-credi
